name: OAL-web CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build
  
